# Generated by Django 5.2.6 on 2025-09-18 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="content",
            field=models.TextField(help_text="Enter note content"),
        ),
        migrations.AlterField(
            model_name="note",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, help_text="Time note was created"
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="title",
            field=models.CharField(help_text="Enter note title", max_length=200),
        ),
    ]
